---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jupyternb-pipeline
  labels:
    app: jupyternb
spec:
  params:
    - name: git_ref
      type: string
    - name: git_ref_type
      type: string
    - name: repo
      type: string
    - name: repo_full_name
      type: string
    - name: pipelinerun_name
      type: string
    - name: git_tag_commit_sha
      type: string
    - name: git_repo_desc
      type: string
    - name: git_http_url
      type: string
    - name: git_tag_author
      type: string
  resources:
    - name: git-repo
      type: git
    - name: s2i-thoth
      type: image
    - name: ubi
      type: image

  tasks:
    - name: configuration
      taskRef:
        name: configuration
      resources:
        inputs:
          - name: repo
            resource: git-repo

    - name: jupyternb-build-release-run
      taskRef:
        name: jupyternb-build-release
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: git_ref_type
          value: $(params.git_ref_type)
        - name: repo
          value: $(params.repo)
        - name: git_tag_commit_sha
          value: $(params.git_tag_commit_sha)
        - name: git_repo_desc
          value: $(params.git_repo_desc)
        - name: git_http_url
          value: $(params.git_http_url)
        - name: git_tag_author
          value: $(params.git_tag_author)
        - name: base_image
          value: $(tasks.configuration.results.base-image)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
