apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: git-template
  labels:
    app: jupyternb
spec:
  params:
    - name: git_ref
      description: Git reference value.
    - name: git_ref_type
      description: Type of ref Tag or Branch.
    - name: repo
      description: The git repository.
    - name: repo_full_name
      description: The git repository full name.
    - name: repo_url
      description: The git repository url
    - name: pipelinerun_name
      description: pipelinerun associated.
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-jupyternb-$(params.repo)-$(uid)
        labels:
          app: jupyternb
          component: pipelinerun-jupyternb-$(params.repo)
      spec:
        serviceAccountName: jupyternb
        pipelineRef:
          name: jupyternb-pipeline
        params:
          - name: git_ref
            value: $(params.git_ref)
          - name: git_ref_type
            value: $(params.git_ref_type)
          - name: repo
            value: $(params.repo)
          - name: repo_full_name
            value: $(params.repo_full_name)
          - name: pipelinerun_name
            value: pipelinerun-jupyternb-$(params.repo)-$(uid)
        resources:
          - name: git-repo
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: master
                - name: url
                  value: $(params.repo_url)
          - name: s2i-custom-notebook
            resourceRef:
              name: s2i-custom-notebook
          - name: s2i-thoth
            resourceRef:
              name: thoth-s2i
          - name: ubi
            resourceRef:
              name: ubi8
