---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyternb-webhook-binding
  labels:
    app: jupyternb
subjects:
- kind: ServiceAccount
  name: jupyternb-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jupyternb-role

---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: jupyternb-webhook-edit
  labels:
    app: jupyternb
subjects:
- kind: ServiceAccount
  name: jupyternb-webhook
roleRef:
  kind: Role
  name: edit
