apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyternb-webhook
  labels:
    app: jupyternb
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: jupyternb
  namespace: jupyternb
secrets:
  - name: auth-secret
  - name: gitlab-secret
